// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALds7zsUW3n15gP9QOLzJHuAupLUA_pjU',
    appId: '1:766952734433:web:0100d99b84fc8f9bca01a0',
    messagingSenderId: '766952734433',
    projectId: 'marcketapp-25ac2',
    authDomain: 'marcketapp-25ac2.firebaseapp.com',
    databaseURL: 'https://marcketapp-25ac2-default-rtdb.firebaseio.com',
    storageBucket: 'marcketapp-25ac2.firebasestorage.app',
    measurementId: 'G-9LV2YDJHKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARGAn5xnUPnomchx9MBd9JfZAg7VMKOqA',
    appId: '1:766952734433:android:048cb9d1a80f498cca01a0',
    messagingSenderId: '766952734433',
    projectId: 'marcketapp-25ac2',
    databaseURL: 'https://marcketapp-25ac2-default-rtdb.firebaseio.com',
    storageBucket: 'marcketapp-25ac2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdmrxIjZV25g12iKw5HfQFCW6Lj5hAzh8',
    appId: '1:766952734433:ios:0c4a0ca7989c4a7fca01a0',
    messagingSenderId: '766952734433',
    projectId: 'marcketapp-25ac2',
    databaseURL: 'https://marcketapp-25ac2-default-rtdb.firebaseio.com',
    storageBucket: 'marcketapp-25ac2.firebasestorage.app',
    iosBundleId: 'com.example.marcketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdmrxIjZV25g12iKw5HfQFCW6Lj5hAzh8',
    appId: '1:766952734433:ios:0c4a0ca7989c4a7fca01a0',
    messagingSenderId: '766952734433',
    projectId: 'marcketapp-25ac2',
    databaseURL: 'https://marcketapp-25ac2-default-rtdb.firebaseio.com',
    storageBucket: 'marcketapp-25ac2.firebasestorage.app',
    iosBundleId: 'com.example.marcketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALds7zsUW3n15gP9QOLzJHuAupLUA_pjU',
    appId: '1:766952734433:web:9c15b5830b2646c6ca01a0',
    messagingSenderId: '766952734433',
    projectId: 'marcketapp-25ac2',
    authDomain: 'marcketapp-25ac2.firebaseapp.com',
    databaseURL: 'https://marcketapp-25ac2-default-rtdb.firebaseio.com',
    storageBucket: 'marcketapp-25ac2.firebasestorage.app',
    measurementId: 'G-NXGLMK6Z0P',
  );

}